Repository Logarithm-Labs/go-hyperliquid, pull requests merged in 2025-02, with the labels that each got.

#17 Exchange API: Add Cloid Support for Order Placing and Cancellation
  hyperliquid/consts.go
  hyperliquid/convert.go
  hyperliquid/exchange_service.go
  hyperliquid/exchange_types.go
  hyperliquid/hyperliquid_test.go
Labels: tests, exchange

#16 Add a test for quick-start
  hyperliquid/hyperliquid_test.go
Labels: tests

#22 Make pre-release updates.
  hyperliquid/client.go
  hyperliquid/consts.go
  hyperliquid/convert.go
  hyperliquid/convert_test.go
  hyperliquid/exchange_service.go
  hyperliquid/exchange_test.go
  hyperliquid/exchange_types.go
  hyperliquid/hyperliquid_test.go
  hyperliquid/info_test.go
Labels: enhancement, dependencies

#19 Fix nonce collisions
  hyperliquid/utils.go
Labels: bug
